name: Crypto Market Analysis

on:
  schedule:
    - cron: "5 * * * *"      # دقیقه 05 هر ساعت (UTC) ~ 35 دقیقه به وقت ایران
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: market-analysis
  cancel-in-progress: true

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas numpy requests yfinance

      # (اختیاری) اگر می‌خواهی state اولیه باشد:
      # - run: echo "{}" > market_state.json

      - name: Run Market Analysis
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          set -e
          UTC_HOUR=$(date -u +%H)
          if [ $((10#$UTC_HOUR % 4)) -eq 0 ]; then
            echo "📊 Running 4h analysis..."
            python crypto_market_analyzer.py --manual
          else
            echo "🕐 Running hourly analysis..."
            python crypto_market_analyzer.py --manual
          fi

      - name: Upload Logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: analysis-logs
          path: |
            market_analyzer.log
            market_state.json
