name: Radar MTF Cron

on:
  workflow_dispatch:      # اجرای دستی برای تست
  schedule:
    - cron: "5 */4 * * *" # هر 4 ساعت در دقیقه 05 (UTC)

jobs:
  run:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run scanner
        run: |
          python live_radar_telegram.py
